#Explosives, by Nity6000.
#Version 1.1 Release
#Succeeder to "Simple Grenades"
#Link to "Simple Grenades" on Bukkit -> https://dev.bukkit.org/projects/simple-grenades
#Link to "Simple Grenades" on Spigot -> https://www.spigotmc.org/resources/simple-grenades.46685/
#Yes I know this is a short config 
#Let me know if I should add more to it
#All Rights Reserved

Version Identifier: '&aExplosives 1.1'